// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v0.0.1-dev
//     生成时间: 2025-12-27 20:17:11
//     设计文件: form1window.ui
//     用户文件: form1window.go
//     功能描述: 基于 ENERGY GUI 框架的实现, 包含UI组件创建
// ==============================================================================

package app

import (
	"github.com/energye/energy/v3/window"
	"github.com/energye/energy/v3/wv"
	"github.com/energye/lcl/lcl"
)

type TForm1Window struct {
	window.TWindow
	BrowserWindow1 wv.IWebview
}

var Form1Window TForm1Window

// FormCreate 窗体创建接口实现. 自动调用
func (m *TForm1Window) FormCreate(sender lcl.IObject) {
	// 设置窗体属性
	m.SetCaption("Form1")
	m.SetHeight(469)
	m.SetLeft(0)
	m.SetName("Form1Window")
	m.SetTop(0)
	m.SetWidth(737)
	// 初始化组件
	m.initComponents()
	m.OnFormCreate(sender)
}

// initComponents 初始化组件
func (m *TForm1Window) initComponents() {
	m.BrowserWindow1 = wv.NewWebview(m)
	m.BrowserWindow1.SetParent(m)
}
