// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v1.0.0
//     生成时间: 2026-04-03 23:07:12
//     设计文件: form1.ui
//     用户文件: form1.go
//     功能描述: 基于 ENERGY GUI 框架的实现, 包含UI组件创建
// ==============================================================================

package app

import (
	"github.com/energye/energy/v3/window"
	"github.com/energye/energy/v3/wv"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	lclTypes "github.com/energye/lcl/types"
)

type TForm1 struct {
	window.TWindow
	SynEdit1            lcl.ISynEdit
	Webview1            wv.IWebview
	Button1             lcl.IButton
	ProgressBar1        lcl.IProgressBar
	LazVirtualDrawTree1 lcl.ILazVirtualDrawTree
	ColorBox1           lcl.IColorBox
}

var Form1 TForm1

// FormCreate 窗体创建接口实现. 自动调用
func (m *TForm1) FormCreate(sender lcl.IObject) {
	m.TWindow.InternalBeforeFormCreate()
	// 设置窗体属性
	m.SetCaption("Form1")
	m.SetHeight(534)
	m.SetLeft(0)
	m.SetName("Form1")
	m.SetTop(0)
	m.SetWidth(981)
	// 初始化组件
	m.initComponents()
	// 调用用户创建窗体事件
	m.OnFormCreate(sender)
	m.TWindow.FormCreate(sender)
}

// OnShow 窗口显示事件
func (m *TForm1) OnShow(sender lcl.IObject) {
	m.TWindow.OnShow(sender)
	m.OnFormShow(sender)
}

// OnCloseQuery 窗体关闭前询问事件
func (m *TForm1) OnCloseQuery(sender lcl.IObject, canClose *bool) {
	if !m.OnFormCloseQuery(sender, canClose) {
		m.TWindow.OnCloseQuery(sender, canClose)
	}
}

// OnClose 仅当 OnCloseQuery 中 CanClose 被设置为 True 后会触发
func (m *TForm1) OnClose(sender lcl.IObject, closeAction *types.TCloseAction) {
	if !m.OnFormClose(sender, closeAction) {
		m.TWindow.OnClose(sender, closeAction)
	}
}

// initComponents 初始化组件
func (m *TForm1) initComponents() {
	// 组件初始化和设置属性
	m.SynEdit1 = lcl.NewSynEdit(m)
	m.SynEdit1.SetAlign(lclTypes.AlLeft)
	m.SynEdit1.SetHeight(510)
	m.SynEdit1.SetLeft(0)
	m.SynEdit1.SetName("SynEdit1")
	m.SynEdit1.SetTop(0)
	m.SynEdit1.SetWidth(246)
	m.SynEdit1.SetParent(m)

	m.Webview1 = wv.NewWebview(m)
	m.Webview1.SetAlign(lclTypes.AlCustom)
	m.Webview1.SetAnchors(lclTypes.NewSet(lclTypes.AkBottom, lclTypes.AkLeft, lclTypes.AkRight, lclTypes.AkTop))
	m.Webview1.SetCaption("Webview1")
	m.Webview1.SetHeight(510)
	m.Webview1.SetLeft(409)
	m.Webview1.SetName("Webview1")
	m.Webview1.SetTop(0)
	m.Webview1.SetWidth(498)
	m.Webview1.SetParent(m)

	m.Button1 = lcl.NewButton(m)
	m.Button1.SetCaption("Button1")
	m.Button1.SetHeight(25)
	m.Button1.SetLeft(262)
	m.Button1.SetName("Button1")
	m.Button1.SetTop(11)
	m.Button1.SetWidth(75)
	m.Button1.SetParent(m)

	m.ProgressBar1 = lcl.NewProgressBar(m)
	m.ProgressBar1.SetHeight(20)
	m.ProgressBar1.SetLeft(261)
	m.ProgressBar1.SetName("ProgressBar1")
	m.ProgressBar1.SetTop(58)
	m.ProgressBar1.SetWidth(100)
	m.ProgressBar1.SetParent(m)

	m.LazVirtualDrawTree1 = lcl.NewLazVirtualDrawTree(m)
	m.LazVirtualDrawTree1.SetHeight(100)
	m.LazVirtualDrawTree1.SetLeft(252)
	m.LazVirtualDrawTree1.SetName("LazVirtualDrawTree1")
	m.LazVirtualDrawTree1.SetTop(101)
	m.LazVirtualDrawTree1.SetWidth(143)
	m.LazVirtualDrawTree1.SetParent(m)

	m.ColorBox1 = lcl.NewColorBox(m)
	m.ColorBox1.SetHeight(35)
	m.ColorBox1.SetLeft(262)
	m.ColorBox1.SetName("ColorBox1")
	m.ColorBox1.SetTop(232)
	m.ColorBox1.SetWidth(100)
	m.ColorBox1.SetParent(m)

}
