// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v1.0.0
//     生成时间: 2026-04-03 23:07:12
//     设计文件: form1.ui
//     用户文件: form1.go
//     功能描述: 基于 ENERGY GUI 框架的实现, 包含UI组件创建
// ==============================================================================

package app

import (
	"fmt"
	"github.com/energye/energy/v3/window"
	"github.com/energye/energy/v3/wv"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	lclTypes "github.com/energye/lcl/types"
	"github.com/energye/lcl/types/colors"
	wvw2 "github.com/energye/wv/windows"
)

type TForm1 struct {
	window.TWindow
	box1         lcl.IPanel
	box2         lcl.IPanel
	Webview1     wv.IWebview
	SwitchButton lcl.IButton
}

var Form1 TForm1

// FormCreate 窗体创建接口实现. 自动调用
func (m *TForm1) FormCreate(sender lcl.IObject) {
	//m.TWindow.InternalBeforeFormCreate()
	// 设置窗体属性
	m.SetCaption("Form1")
	m.SetHeight(534)
	m.SetLeft(0)
	m.SetName("Form1")
	m.SetTop(0)
	m.SetWidth(981)
	// 初始化组件
	m.initComponents()
	// 调用用户创建窗体事件
	m.OnFormCreate(sender)
	//m.TWindow.FormCreate(sender)
}

// OnShow 窗口显示事件
func (m *TForm1) OnShow(sender lcl.IObject) {
	m.TWindow.OnShow(sender)
	m.OnFormShow(sender)
}

// OnCloseQuery 窗体关闭前询问事件
func (m *TForm1) OnCloseQuery(sender lcl.IObject, canClose *bool) {
	if !m.OnFormCloseQuery(sender, canClose) {
		m.TWindow.OnCloseQuery(sender, canClose)
	}
}

// OnClose 仅当 OnCloseQuery 中 CanClose 被设置为 True 后会触发
func (m *TForm1) OnClose(sender lcl.IObject, closeAction *types.TCloseAction) {
	if !m.OnFormClose(sender, closeAction) {
		m.TWindow.OnClose(sender, closeAction)
	}
}

// initComponents 初始化组件
func (m *TForm1) initComponents() {
	// 组件初始化和设置属性

	m.box1 = lcl.NewPanel(m)
	m.box1.SetAlign(types.AlLeft)
	m.box1.SetParent(m)
	m.box1.SetWidth(400)
	m.box1.SetColor(colors.ClBlue)

	m.box2 = lcl.NewPanel(m)
	//m.box2.SetAlign(types.AlRight)
	m.box2.SetParent(m)
	m.box2.SetWidth(400)
	m.box2.SetHeight(m.Height())
	m.box2.SetLeft(500)
	m.box2.SetAnchors(types.NewSet(types.AkLeft, types.AkTop, types.AkRight, types.AkBottom))
	m.box2.SetColor(colors.ClYellow)

	windParent2 := wvw2.NewWindowParent(m)
	windParent2.SetDoubleBuffered(true)
	windParent2.SetAlign(types.AlClient)
	windParent2.SetParent(m.box2)

	m.Webview1 = wv.NewWebview(m)
	m.Webview1.SetAlign(lclTypes.AlClient)
	m.Webview1.SetCaption("Webview1")
	m.Webview1.SetHeight(510)
	m.Webview1.SetLeft(409)
	m.Webview1.SetName("Webview1")
	m.Webview1.SetTop(0)
	m.Webview1.SetWidth(498)
	m.Webview1.SetParent(m.box1)

	switchPanel := false
	wv2 := m.Webview1.(*wv.TWebview)
	_ = wv2
	winParent1 := wv2.WindowParent().(wvw2.IWVWindowParent)

	m.SwitchButton = lcl.NewButton(m)
	m.SwitchButton.SetParent(m)
	m.SwitchButton.SetLeft(450)
	m.SwitchButton.SetCaption("切换不同Panel")
	m.SwitchButton.SetOnClick(func(sender lcl.IObject) {
		fmt.Println("切换不同Panel")
		switchPanel = !switchPanel
		browser := wv2.Browser().(wvw2.IWVBrowser)
		if switchPanel {
			winParent1.SetBrowser(nil)
			windParent2.SetBrowser(browser)
			browser.SetParentWindow(windParent2.Handle())
			lcl.RunOnMainThreadAsync(func(id uint32) {
				browser.NotifyParentWindowPositionChanged()
				windParent2.UpdateSize()
			})
		} else {
			windParent2.SetBrowser(nil)
			winParent1.SetBrowser(browser)
			browser.SetParentWindow(winParent1.Handle())
			lcl.RunOnMainThreadAsync(func(id uint32) {
				browser.NotifyParentWindowPositionChanged()
				winParent1.UpdateSize()
			})
		}
	})
}
