// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v1.0.0
//     生成时间: 2026-04-03 23:07:12
//     设计文件: form1.ui
//     用户文件: form1.go
//     功能描述: 基于 ENERGY GUI 框架的实现, 包含UI组件创建
// ==============================================================================

package app

import (
	"fmt"
	"github.com/energye/energy/v3/platform/linux/webkit2gtk"
	"github.com/energye/energy/v3/window"
	"github.com/energye/energy/v3/wv"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	lclTypes "github.com/energye/lcl/types"
	"github.com/energye/lcl/types/colors"
	wvw2 "github.com/energye/wv/linux"
	"unsafe"
)

type TForm1 struct {
	window.TWindow
	box1         lcl.IPanel
	box2         lcl.IPanel
	Webview1     wv.IWebview
	SwitchButton lcl.IButton
}

var Form1 TForm1

// FormCreate 窗体创建接口实现. 自动调用
func (m *TForm1) FormCreate(sender lcl.IObject) {
	//m.TWindow.InternalBeforeFormCreate()
	// 设置窗体属性
	m.SetPosition(types.PoScreenCenter)
	m.SetCaption("Form1")
	m.SetHeight(600)
	m.SetWidth(900)
	// 初始化组件
	m.initComponents()
	// 调用用户创建窗体事件
	m.OnFormCreate(sender)
	m.TWindow.FormCreate(sender)
}

// OnShow 窗口显示事件
func (m *TForm1) OnShow(sender lcl.IObject) {
	m.Webview1.CreateBrowser()
	m.Webview1.Update()
	winParent1 := m.Webview1.WindowParent().(wvw2.IWkWebviewParent)
	winParent1.SetBoundsRect(m.box1.BoundsRect())
}

// initComponents 初始化组件
func (m *TForm1) initComponents() {
	m.box1 = lcl.NewPanel(m)
	m.box1.SetAnchors(types.NewSet(types.AkLeft, types.AkTop, types.AkBottom))
	m.box1.SetCaption("box1")
	m.box1.SetWidth(400)
	m.box1.SetHeight(m.Height())
	m.box1.SetColor(colors.Cl3DHiLight)
	m.box1.SetParent(m)

	m.box2 = lcl.NewPanel(m)
	m.box2.SetCaption("box2")
	m.box2.SetTop(10)
	m.box2.SetLeft(450)
	m.box2.SetWidth(440)
	m.box2.SetHeight(m.Height() - 20)
	m.box2.SetAnchors(types.NewSet(types.AkLeft, types.AkTop, types.AkRight, types.AkBottom))
	m.box2.SetColor(colors.ClYellow)
	m.box2.SetParent(m)

	windParent2 := wvw2.NewWebviewParent(m)
	windParent2.SetDoubleBuffered(true)
	windParent2.SetAlign(types.AlClient)
	windParent2.SetParent(m.box2)
	//winParent2gtkScrolledWindow := gtk3.AsScrolledWindow(unsafe.Pointer(windParent2.ScrolledWindow()))

	m.Webview1 = wv.NewWebview(m)
	m.Webview1.SetAlign(lclTypes.AlClient)
	m.Webview1.SetCaption("Webview1")
	m.Webview1.SetName("Webview1")
	m.Webview1.SetTop(0)
	m.Webview1.SetWidth(498)
	m.Webview1.SetParent(m.box1)

	winParent1 := m.Webview1.WindowParent().(wvw2.IWkWebviewParent)
	//winParent1gtkScrolledWindow := gtk3.AsScrolledWindow(unsafe.Pointer(winParent1.ScrolledWindow()))

	webkit2wv := webkit2gtk.AsWebkit2(unsafe.Pointer(m.Webview1.Browser().(wvw2.IWkWebview).WebView()))
	webkit2wv.Ref()

	m.SwitchButton = lcl.NewButton(m)
	m.SwitchButton.SetParent(m)
	m.SwitchButton.SetLeft(450)
	m.SwitchButton.SetCaption("切换不同Panel")
	switchPanel := false
	m.SwitchButton.SetOnClick(func(sender lcl.IObject) {
		fmt.Println("切换不同Panel")
		switchPanel = !switchPanel
		browser := m.Webview1.Browser().(wvw2.IWkWebview)
		if switchPanel {
			winParent1.SetWebview(nil)
			windParent2.SetWebview(browser)
			lcl.RunOnMainThreadAsync(func(id uint32) {
				//windParent2.UpdateSize(m.box2.Width(), m.box2.Height())
				windParent2.SetBoundsRect(m.box2.BoundsRect())
			})
		} else {
			windParent2.SetWebview(nil)
			winParent1.SetWebview(browser)
			lcl.RunOnMainThreadAsync(func(id uint32) {
				//winParent1.UpdateSize(m.box1.Width(), m.box1.Height())
				winParent1.SetBoundsRect(m.box1.BoundsRect())
			})
		}
	})
}
